_base_: cnn_cls_train.yaml

imports:
  - core.networks.gan_toy.framework
  - core.models.gan_toy.gan_model
  - core.losses.gan_loss

network:
  name: toy_gan_network
  noise_dim: 16
  data_dim: 16

model:
  name: toy_gan_model

loss:
  name: toy_gan_loss
