_base_: cnn_cls_train.yaml

imports:
  - core.networks.diffusion_toy.unet
  - core.models.diffusion_toy.diffusion_model
  - core.losses.diffusion_loss

network:
  name: toy_denoiser
  data_dim: 16
  hidden_dim: 32

model:
  name: toy_diffusion_model

loss:
  name: toy_diffusion_loss
